version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: apinode
      MYSQL_USER: joao
      MYSQL_PASSWORD: senha123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306" 
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
